### PR TITLE
Deprecate the QueueInspect function

### LINKED ISSUE #167: Deprecate QueueInspect
https://github.com/rabbitmq/amqp091-go/discussions/165

The function does not add any real benefit over a passive queue declaration. If this function is called on a queue that has any custom declaration parameters (like an exclusive queue), it will always fail.

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #167

https://github.com/rabbitmq/amqp091-go/discussions/165

### CODE REVIEW

**Review by Zerpet — APPROVED** [review]
🚀

**Comment by Zerpet** [comment]
From semver point of view, is it ok to deprecate a function in a patch release? 🤔

**Comment by lukebakken** [comment]
@Zerpet thanks for checking that.

**Comment by Zerpet** [comment]
Now that 1.6.1 is out, are there any blockers to merge this PR?

**Comment by lukebakken** [comment]
> Now that 1.6.1 is out, are there any blockers to merge this PR?

There's no guarantee there won't be a `1.6.2` version. It's fine to leave this PR open until we're certain the next version to ship is `1.7.0`.

**Pull request merged**
