### PR TITLE
Set channels and allocator to nil in shutdown

### PR DESCRIPTION
**Pull request by lukebakken**
Follow up to #171

cc @Zerpet

cc @jxsl13 since it may be interesting

### CODE REVIEW

**Comment by jxsl13** [comment]
I think due to the slash in the branch name, it's not trivially possible to go get this branch as dependency: 
```
go: github.com/rabbitmq/amqp091-go@lukebakken/nil-for-cleanup: invalid version: version "lukebakken/nil-for-cleanup" invalid: disallowed version string
```

**Comment by jxsl13** [comment]
tests still work.

**Review by Zerpet — APPROVED** [review]
I added a test case to ensure that `Connection.Channel()` won't panic, when called on a closed connection. A user may try to use a closed connection. In such case, the library should return an error (not panic).

**Comment by Zerpet** [comment]
@lukebakken happy with the code as is. Feel free to add your review to my test case before merging :)

**Comment by lukebakken** [comment]
@jxsl13 - I'll keep that in mind for future PRs (don't use a slash). Thanks for testing.

**Comment by jxsl13** [comment]
Thanks for maintaining the library :)

**Comment by Zerpet** [comment]
GitHub Actions is having a bad day and has queued the CodeQL action for 35 minutes (and counting). Given that previous commits passed the CI ✅ And that main is also green, I'm going to merge as-is.

**Pull request merged**
