### PR TITLE
Supply library-defined props with NewConnectionProperties

### LINKED ISSUE #152: Allow re-using default connection config (custom properties)
When using `SetClientConnectionName` (to identify connections in RabbitMQ) it is impossible to use the built-in client properties of this library.

As per examples:
```go
	config := amqp.Config{Properties: amqp.NewConnectionProperties()}
	config.Properties.SetClientConnectionName("sample-consumer")
	c.conn, err = amqp.DialConfig(amqpURI, config)
```

This results in default properties being ignored in [openTune](https://github.com/rabbitmq/amqp091-go/blob/dd91ad527eb99b6c81e629ae994d808a1a7ec527/connection.go#L877-L883).
```go
	if len(config.Properties) == 0 {
		config.Properties = Table{
			"product":  defaultProduct,
			"version":  buildVersion,
			"platform": platform,
		}
	}
```

In the end we get either `{"connection_name": "sample-consumer"}` or `{"product": "AMQP 0.9.1 Client", "version": "1.5.0", "platform": "golang"}`. Never both. Unless copied to client code with the risk of being outdated.

Of course, clients providing their own properties might not want to have these present. Because of that it would not make sense to "provide defaults if not present" in the properties table.

However some kind of union between default properties and client provided metadata would be beneficial. 

Possible solutions:
1. Expose `amqp.DefaultConfig()` that has `Heartbeat`, `Locale` and `Properties` set.
With this, `amqp.Dial(url)` would be equal to `amqp.DialConfig(url, amqp.DefaultConfig())` and setting other properties would go as follows:
```go
config := amqp.DefaultConfig()
config.Properties.SetClientConnectionName("sample-consumer")
c.conn, err := amqp.DialConfig(amqpURI, config)
```
2. Expose `amqp.DefaultConfigProperties()` 
```go
	config := amqp.Config{Properties: amqp.DefaultConfigProperties()}
	config.Properties.SetClientConnectionName("sample-consumer")
	c.conn, err = amqp.DialConfig(amqpURI, config)
```
3. Both of the above if necessary
4. Use other ways of using config, e.g. functional option pattern

Names TBD. 

I'm up to create a Pull Request with changes, but let's discuss what are your expectations first.

### PR DESCRIPTION
**Pull request by slagiewka**
Fixes #152

### CODE REVIEW

**Comment by slagiewka** [comment]
I wasn't too sure about testing this. What would be your expectations for this? A simple check if `NewConnectionProperties` always returns the fixed set?

**Comment by Zerpet** [comment]
Thank you for the PR! Yes, I think a simple check to assert the existence of the expected keys and values would suffice. The keys `platform` and `product` should not change overtime. The key `version` is changing between releases, so we could assert that its value is a valid semver string.

**Comment by slagiewka** [comment]
> Thank you for the PR! Yes, I think a simple check to assert the existence of the expected keys and values would suffice. The keys `platform` and `product` should not change overtime. The key `version` is changing between releases, so we could assert that its value is a valid semver string.

I added a test for both. However I'm not too sure about the version string being checked here. Ideally it would be valid whether or not we have something (e.g. `NewConnectionProperties`) using it and testing it on its own.

**Review by lukebakken — APPROVED** [review]
Thank you for your contribution!

**Review by Zerpet — APPROVED** [review]

**Comment by Zerpet** [comment]
> > Thank you for the PR! Yes, I think a simple check to assert the existence of the expected keys and values would suffice. The keys `platform` and `product` should not change overtime. The key `version` is changing between releases, so we could assert that its value is a valid semver string.
> 
> I added a test for both. However I'm not too sure about the version string being checked here. Ideally it would be valid whether or not we have something (e.g. `NewConnectionProperties`) using it and testing it on its own.

I understand your point, and I think it's a matter of preference. I personally want my tests to be red when/if I do something (very) wrong, like setting the version string to `foo`. Similarly, I think it's ok to assert on values for product and platform, because these values become part of the contract when the constructor sets them; therefore, if we break this contract, tests should be red.

Thank you for your contribution!

**Pull request merged**
