### PR TITLE
Fix race condition on confirms

### PR DESCRIPTION
**Pull request by calloway-jacob**
This PR fixes Issue #182

### CODE REVIEW

**Review by lukebakken — APPROVED** [review]
@Zerpet changing `Publish` to `publish` is an API change, but I consider it being public to be a bug in the first place. What do you think?

**Review by Zerpet — APPROVED** [review]

**Comment by Zerpet** [comment]
> @Zerpet changing `Publish` to `publish` is an API change, but I consider it being public to be a bug in the first place. What do you think?

I'm happy with that. `confirm` is unexported struct, so it's not even a breaking change, since user code can't use it.

**Comment by Zerpet** [comment]
Thank you @calloway-jacob !! 🚀

**Comment by calloway-jacob** [comment]
@Zerpet and @lukebakken Very happy to help!

**Pull request merged**
