### PR TITLE
Update spec091.go

### PR DESCRIPTION
**Pull request by pinkfish**
Fix up a go lint error with no space between the // and the text.

### CODE REVIEW

**Comment by lukebakken** [comment]
@Zerpet is this file auto-generated? I will see if I can figure that out.

@pinkfish we do go lint checking as part of GitHub actions. How was this formatting missed?

**Comment by pinkfish** [comment]
I think there is more strict lint checking in some areas :)

**Comment by lukebakken** [comment]
> I think there is more strict lint checking in some areas :)

@pinkfish - That's good to know, but I'm interested in _specific details_:
* Which linter are you using?
* How can I run it to see this particular formatting issue being raised as an error?

As @Zerpet said, as far as our current linter is concerned, there is no issue here, so we'll need more information.

**Review by lukebakken — CHANGES_REQUESTED** [review]
The code that generates `spec091.go` must be updated, and re-run.

**Comment by pinkfish** [comment]
I think it is go vet buildtag

It is because the no space after a // should be a compiler tag for the +build pieces.

**Comment by lukebakken** [comment]
@pinkfish hmm this is what I get when I run that command:

```
C:\Users\lbakken\development\rabbitmq\amqp091-go [main ≡]
> go vet buildtag
package buildtag is not in std (C:\Users\lbakken\scoop\apps\go\current\src\buildtag)
```

It seems like `-buildtag` is the correct argument. But, when I run it, no errors are returned:

```
C:\Users\lbakken\development\rabbitmq\amqp091-go [main ≡]
> go vet -all
C:\Users\lbakken\development\rabbitmq\amqp091-go [main ≡]
> go vet -buildtag
```

**Review by lukebakken — APPROVED** [review]

**Pull request merged**
