### PR TITLE
Ensure code is formatted

### PR DESCRIPTION
**Pull request by lukebakken**
Also bump Windows dep versions

### CODE REVIEW

**Review by Zerpet — COMMENTED** [review]
Looks good. I have a few cosmetic adjustments in mind. I'll assign you as reviewer after I push my changes 👀

**Comment by Zerpet** [comment]
For some reason, it is failing in GitHub actions `build-linux`, but it is succeeding in my local machine (using `act`) and in build-windows 🤯

**Comment by Zerpet** [comment]
Ok, so the problem is that the Action merges the PR, somehow, and then runs our `make check-fmt`. It is pulling from `main` the changes we merged recently in #145. The changes in #145 need formatting, and that's what's causing havoc.

It's not the best developer experience, but it ensures that folks rebase their branches against the `main` branch before the PR checks pass.

Why it doesn't fail on windoze is a mystery to me ❗

**Comment by Zerpet** [comment]
@lukebakken we can merge main into your feature branch (ugh, imo) or rebase the feature branch against the main branch. Either will make the checks pass. I don't want to rebase your branch myself because it will create git weirdness in your local clone.

**Comment by lukebakken** [comment]
@Zerpet do whatever works. I certainly don't mind if you force push to my branch because actually it shouldn't affect me locally and if it does, whatever. I'll check this out tomorrow.

**Pull request merged**
